add_rules("mode.debug", "mode.release")

add_requires("raylib")
add_requires("abseil")
add_requires("taskflow")
add_requires("gtest")
add_requires("benchmark")
add_requires("meshoptimizer")
add_requires("bvh")

target("main")
set_default(true)
set_kind("binary")
set_languages("c++23")
set_rundir("$(projectdir)")
add_files("src/*.cpp")
add_packages("raylib", "taskflow", "abseil", "meshoptimizer", "bvh")
add_includedirs("lib")

target("tests")
set_default(false)
set_kind("binary")
set_languages("c++23")
add_files("tests/*.cpp")
add_packages("gtest", "taskflow", "raylib", "abseil")
add_includedirs("lib")

target("bench")
set_default(false)
set_kind("binary")
set_languages("c++23")
add_files("benches/*.cpp")
add_packages("benchmark", "taskflow", "raylib", "abseil")
add_includedirs("lib")
