@startuml component-some
skinparam linetype ortho

title rydz_ecs - Diagram komponentów

package "Sprite Entity" {
[Entity] as Entity
[Transform] as Transform
[Visiblity] as Visiblity
[Material] as Material
[Texture] as Texture
}


Transform -> Entity
Visiblity -> Entity
Material -> Entity
Texture -> Entity

@enduml

@startuml component
#skinparam linetype ortho
title rydz_ecs - Diagram komponentów

package "Rdzeń ECS" {
  [Entity\nMenedżer encji] as Entity
  [Storage\nSparseSetStorage\nHashMapStorage] as Storage
  [World\nEncje + Komponenty\n+ Zasoby + Ticki] as World
  [Resource\nSingletony z wymazaniem typu] as Resource
  [Ticks\nWykrywanie zmian] as Ticks
}

package "System zapytań" {
  [Query\nQuery<Ts...>] as Query
  [Filter\nWith Without Added\nChanged Or] as Filter
  [Access\nSystemAccess\nŚledzenie odczytu/zapisu] as Access
}

package "Wykonanie" {
  [System\nISystem\nFunctionSystem\nWstrzykiwanie zależności] as System
  [Schedule\nSortowanie topologiczne\nGrupowanie równoległe\nTaskflow] as Schedule
  [Condition\nrun_if\nrun_once] as Condition
  [Command\nCmd\nCommandQueue\nOdroczone mutacje] as Command
}

package "Aplikacja" {
  [App\nZarządzanie pluginami\nOrkiestracja harmonogramów\nGłówna pętla] as App
  [Plugin\nIPlugin\nFunctionPlugin] as Plugin
  [State\nState<S>\nNextState<S>\nOnEnter / OnExit] as State
  [Event\nEvents<E>\nEventReader\nEventWriter\nPodwójne buforowanie] as Event
}

package "Domena" {
  [Input\nKlawiatura / Mysz] as Input
  [Asset\nAssetServer\nHandle<T>\nAsynchroniczne ładowanie] as Asset
  [Hierarchy\nRodzic / Dzieci] as Hierarchy
  [Time\nName] as CoreTypes
}

package "Zewnętrzne" {
  [Raylib\nRenderowanie / Okno] as Raylib
  [Taskflow\nRównoległe wykonanie] as Taskflow
}

World --> Entity
World --> Storage
World --> Resource
Storage --> Ticks
Storage --> Entity

Query --> Storage
Query --> Filter
Query --> Access
Query --> World
Filter --> Ticks

System --> Query
System --> Access
System --> World
Command --> World
Command --> System

Schedule --> System
Schedule --> Condition
Schedule --> Access
Schedule --> Taskflow
Condition --> System

App --> Schedule
App --> World
App --> Plugin
App --> Command
App --> Event
App --> State

State --> Schedule
Event --> System

Input --> App
Input --> Raylib
Asset --> World
Asset --> System
Hierarchy --> Entity
Hierarchy --> World
CoreTypes --> World
@enduml

@startuml component-graphics
skinparam linetype ortho
title rydz_graphics - Diagram komponentów

package "Komponenty sceny" {
  [Transform3D] as Transform3D
  [GlobalTransform] as GlobalTransform
  [Visibility] as Visibility
  [ComputedVisibility] as ComputedVisibility
  [ViewVisibility] as ViewVisibility
  [MeshBounds] as MeshBounds
  [Model3d] as Model3d
  [Mesh3d] as Mesh3d
  [Material3d] as Material3d
  [RenderConfig] as RenderConfig
  [MeshLodGroup] as MeshLodGroup
  [Texture] as Texture
}

package "Kamera i światło" {
  [Camera3DComponent] as Camera3D
  [ActiveCamera] as ActiveCamera
  [Skybox] as Skybox
  [DirectionalLight] as DirectionalLight
  [PointLight] as PointLight
  [AmbientLight] as AmbientLight
}

package "Zasoby" {
  [Assets<rl::Model>] as ModelAssets
  [Assets<rl::Mesh>] as MeshAssets
  [Assets<rl::Texture2D>] as TextureAssets
  [Assets<rl::Sound>] as SoundAssets
  [RenderBatches] as RenderBatches
  [ClearColor] as ClearColor
  [AssetServer] as AssetServer
  [PendingModelLoads] as PendingModelLoads
  [LodConfig] as LodConfig
  [LodHistory] as LodHistory
}

package "Systemy grafiki" {
  [RenderPlugin\nRejestracja zasobów\n+ systemów] as RenderPlugin
  [propagate_transforms] as Propagate
  [compute_visibility] as ComputeVisibility
  [compute_mesh_bounds_system] as ComputeBounds
  [frustum_cull_system] as FrustumCull
  [auto_generate_lods_system] as AutoLod
  [build_render_batches_system] as BuildBatches
  [apply_materials_system] as ApplyMaterials
  [render_system] as RenderSystem
  [process_pending_model_loads] as ProcessLoads
}

package "Zewnętrzne" {
  [Raylib] as Raylib
  [Taskflow] as Taskflow
  [meshoptimizer] as Meshopt
}

RenderPlugin --> AssetServer
RenderPlugin --> ModelAssets
RenderPlugin --> MeshAssets
RenderPlugin --> TextureAssets
RenderPlugin --> SoundAssets
RenderPlugin --> RenderBatches
RenderPlugin --> ClearColor
RenderPlugin --> LodConfig
RenderPlugin --> LodHistory
RenderPlugin --> PendingModelLoads
RenderPlugin --> BuildBatches
RenderPlugin --> RenderSystem
RenderPlugin --> ApplyMaterials
RenderPlugin --> AutoLod
RenderPlugin --> FrustumCull
RenderPlugin --> ComputeBounds
RenderPlugin --> ComputeVisibility
RenderPlugin --> Propagate
RenderPlugin --> ProcessLoads

Transform3D --> GlobalTransform
Visibility --> ComputedVisibility
ComputedVisibility --> ViewVisibility
MeshBounds --> ViewVisibility
Camera3D --> ViewVisibility
ActiveCamera --> ViewVisibility
GlobalTransform --> ViewVisibility

Model3d --> MeshBounds
Model3d --> ModelAssets
Mesh3d --> MeshAssets
Texture --> TextureAssets
Model3d --> RenderBatches
MeshLodGroup --> RenderBatches
Material3d --> RenderBatches
RenderConfig --> RenderBatches
ViewVisibility --> RenderBatches
GlobalTransform --> RenderBatches

AssetServer --> ModelAssets
AssetServer --> TextureAssets
AssetServer --> SoundAssets
ProcessLoads --> PendingModelLoads
ProcessLoads --> ModelAssets

BuildBatches --> RenderBatches
BuildBatches --> ModelAssets

ApplyMaterials --> ModelAssets
ApplyMaterials --> TextureAssets

AutoLod --> ModelAssets
AutoLod --> LodConfig
AutoLod --> LodHistory
AutoLod --> MeshLodGroup
AutoLod --> Meshopt

ComputeVisibility --> Visibility
ComputeVisibility --> ComputedVisibility
ComputeBounds --> Model3d
ComputeBounds --> MeshBounds
ComputeBounds --> ModelAssets
FrustumCull --> MeshBounds
FrustumCull --> ViewVisibility
FrustumCull --> GlobalTransform
FrustumCull --> ComputedVisibility
FrustumCull --> Camera3D
FrustumCull --> Transform3D
FrustumCull --> ActiveCamera
FrustumCull --> Taskflow

RenderSystem --> RenderBatches
RenderSystem --> ModelAssets
RenderSystem --> TextureAssets
RenderSystem --> ClearColor
RenderSystem --> Camera3D
RenderSystem --> ActiveCamera
RenderSystem --> Transform3D
RenderSystem --> Skybox
RenderSystem --> DirectionalLight
RenderSystem --> PointLight
RenderSystem --> Texture
RenderSystem --> Raylib
@enduml

@startuml component-audio
skinparam linetype ortho
title (Przykład) AudioPlugin inspirowany Bevy - Diagram komponentów

package "Komponenty audio" {
  [AudioSink] as AudioSink
  [SpatialAudioSink] as SpatialAudioSink
  [PlaybackSettings] as PlaybackSettings
  [AudioListener] as AudioListener
}

package "Zasoby" {
  [Audio] as Audio
  [AudioChannel<T>] as AudioChannel
  [Assets<AudioSource>] as AudioAssets
  [AudioOutput] as AudioOutput
  [AudioQueue] as AudioQueue
}

package "Systemy audio" {
  [AudioPlugin\nRejestracja zasobów\n+ systemów] as AudioPlugin
  [play_audio_system] as PlayAudio
  [update_sinks_system] as UpdateSinks
  [spatial_audio_system] as SpatialAudio
  [cleanup_finished_system] as CleanupAudio
}

package "Zewnętrzne" {
  [Backend audio\n(cpal/rodio)] as AudioBackend
}

AudioPlugin --> Audio
AudioPlugin --> AudioChannel
AudioPlugin --> AudioAssets
AudioPlugin --> AudioOutput
AudioPlugin --> AudioQueue
AudioPlugin --> PlayAudio
AudioPlugin --> UpdateSinks
AudioPlugin --> SpatialAudio
AudioPlugin --> CleanupAudio

Audio --> AudioAssets
Audio --> AudioChannel
Audio --> AudioQueue
AudioChannel --> AudioQueue

PlayAudio --> AudioQueue
UpdateSinks --> AudioSink
UpdateSinks --> PlaybackSettings
SpatialAudio --> SpatialAudioSink
SpatialAudio --> AudioListener
CleanupAudio --> AudioSink

AudioOutput --> AudioBackend
AudioQueue --> AudioBackend
@enduml

@startuml component-physics
skinparam linetype ortho
title (Przykład) PhysicsPlugin inspirowany Bevy + Jolt - Diagram komponentów

package "Komponenty fizyki" {
  [RigidBody] as RigidBody
  [Collider] as Collider
  [Velocity] as Velocity
  [ExternalForce] as ExternalForce
  [GravityScale] as GravityScale
  [Damping] as Damping
  [Sleeping] as Sleeping
  [LockedAxes] as LockedAxes
  [Sensor] as Sensor
  [CollisionGroups] as CollisionGroups
}

package "Zdarzenia" {
  [CollisionEvent] as CollisionEvent
  [ContactForceEvent] as ContactForceEvent
}

package "Zasoby" {
  [JoltConfiguration] as PhysicsConfig
  [IntegrationParameters] as IntegrationParams
  [PhysicsPipeline] as PhysicsPipeline
  [BroadPhase] as BroadPhase
  [NarrowPhase] as NarrowPhase
  [QueryPipeline] as QueryPipeline
}

package "Systemy fizyki" {
  [PhysicsPlugin\nRejestracja zasobów\n+ systemów] as PhysicsPlugin
  [step_physics_system] as StepPhysics
  [sync_from_physics] as SyncFromPhysics
  [sync_to_physics] as SyncToPhysics
  [emit_collision_events] as EmitEvents
}

package "ECS" {
  [Transform] as Transform
  [GlobalTransform] as GlobalTransform
}

package "Zewnętrzne" {
  [Jolt] as Jolt
}

PhysicsPlugin --> PhysicsConfig
PhysicsPlugin --> IntegrationParams
PhysicsPlugin --> PhysicsPipeline
PhysicsPlugin --> BroadPhase
PhysicsPlugin --> NarrowPhase
PhysicsPlugin --> QueryPipeline
PhysicsPlugin --> StepPhysics
PhysicsPlugin --> SyncFromPhysics
PhysicsPlugin --> SyncToPhysics
PhysicsPlugin --> EmitEvents

StepPhysics --> RigidBody
StepPhysics --> Collider
StepPhysics --> Velocity
StepPhysics --> ExternalForce
StepPhysics --> Jolt
StepPhysics --> PhysicsPipeline
StepPhysics --> BroadPhase
StepPhysics --> NarrowPhase
StepPhysics --> IntegrationParams
StepPhysics --> PhysicsConfig

SyncToPhysics --> Transform
SyncToPhysics --> RigidBody
SyncToPhysics --> Velocity

SyncFromPhysics --> Transform
SyncFromPhysics --> GlobalTransform
SyncFromPhysics --> RigidBody
SyncFromPhysics --> Velocity

EmitEvents --> CollisionEvent
EmitEvents --> ContactForceEvent
EmitEvents --> NarrowPhase
EmitEvents --> RigidBody
EmitEvents --> Collider

Collider --> CollisionGroups
RigidBody --> Sleeping
RigidBody --> LockedAxes
RigidBody --> GravityScale
RigidBody --> Damping
Sensor --> Collider
@enduml

@startuml sequence
title rydz_ecs - Pętla aktualizacji App::update()

participant App
participant Schedules
participant Schedule
participant System
participant World
participant CommandQueue

App -> App: startup()
note over App: PreStartup -> Startup -> PostStartup (uruchomienie)

loop while !WindowShouldClose()
  App -> App: update()
  App -> World: aktualizacja zasobu Time
  App -> World: increment_change_tick()

  loop dla każdego ScheduleLabel (First..Last)
    App -> Schedules: run(label, world)
    Schedules -> Schedule: run(world)
    activate Schedule

    Schedule -> Schedule: build_graph()\nsortowanie topologiczne\ngrupowanie kompatybilnych systemów

    loop dla każdej grupy
      Schedule -> System: run(world)
      activate System

      par równoległe systemy przez Taskflow
        System -> World: zapytanie o komponenty
        World --> System: wyniki
        System -> CommandQueue: push(cmd)
      end

      deactivate System
    end

    Schedule --> Schedules: zakończono
    deactivate Schedule

    App -> CommandQueue: apply(world)
    CommandQueue -> World: spawn / despawn / insert
  end
end
@enduml

@startuml storage
title rydz_ecs - Warstwa przechowywania

package "Warstwa przechowywania" {
  interface IStorage {
    +remove(Entity)
    +has(Entity): bool
    +entities(): span
    +size(): usize
  }

  class "SparseSetStorage<T>" as Sparse {
    -sparse_: vector<u32>
    -dense_: vector<Entity>
    -data_: vector<T>
    -ticks_: vector<ComponentTicks>
    +insert(Entity, T, Tick)
    +get(Entity): T*
    +remove(Entity)
    +for_each(F)
  }

  class "HashMapStorage<T>" as HashMap {
    -map_: unordered_map
    +insert(Entity, T, Tick)
    +get(Entity): T*
    +remove(Entity)
  }

  class "storage_trait<T>" as Trait << (T,#FF7700) trait >> {
    +type Storage
  }
}

package "Dane" {
  class Entity {
    +index: u32
    +generation: u32
  }

  class ComponentTicks {
    +added: Tick
    +changed: Tick
  }
}

Sparse --|> IStorage
HashMap --|> IStorage
Trait ..> Sparse : domyślny
Trait ..> HashMap : alternatywny

Sparse --> Entity
Sparse --> ComponentTicks
HashMap --> Entity
HashMap --> ComponentTicks
@enduml

@startuml activity
title rydz_ecs - Wstrzykiwanie zależności systemu

start

:Rejestracja funkcji systemu;
:Ekstrakcja typów parametrów
przez function_traits<F>;

if (Zawiera Query<Ts...>?) then (tak)
  :Rozwiąż storage z World;
  :Zapisz dostęp odczyt/zapis komponentów;
else (nie)
endif

if (Zawiera Res<T> / ResMut<T>?) then (tak)
  :Wyszukaj zasób w World;
  :Zapisz dostęp odczyt/zapis zasobu;
else (nie)
endif

if (Zawiera Cmd?) then (tak)
  :Wstrzyknij referencję do CommandQueue;
else (nie)
endif

if (Zawiera World?) then (tak)
  :Oznacz jako ekskluzywny
  (brak równoległości);
else (nie)
endif

:Zbuduj SystemAccess;
:Zarejestruj w Schedule;

end
@enduml
