name: ci

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Build tests and main
        shell: bash
        run: |
          xmake f -y -p linux -a x86_64 -m debug
          xmake build tests
          xmake build main

  # nixos:
  #   name: nixos
  #   runs-on: [self-hosted, nixos]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Build tests and main
  #       shell: bash
  #       run: |
  #         nix-shell -p xmake clang --run '
  #           xmake f -y -m debug &&
  #           xmake build tests &&
  #           xmake build main
  #         '

  windows:
    name: windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Build tests and main
        shell: pwsh
        run: |
          xmake f -y -p windows -a x64 -m debug
          xmake build tests
          xmake build main
