name: ci

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
      name: linux
      runs-on: ubuntu-24.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install GCC 15 and dependencies
          run: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
            sudo apt-get update
            sudo apt-get install -y \
              gcc-15 g++-15 \
              libx11-dev libxcursor-dev libxinerama-dev libxrandr-dev libxi-dev \
              libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libpulse-dev

        - name: Setup xmake
          uses: xmake-io/github-action-setup-xmake@v1
          with:
            xmake-version: latest

        - name: Build tests and main
          shell: bash
          run: |
            # Wymuszamy GCC 15 dla projektu i wszystkich zależności
            xmake f -y -p linux -a x86_64 -m debug --cc=gcc-15 --cxx=g++-15
            xmake build -y tests
            xmake build -y main

  windows:
    name: windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build tests and main
        shell: pwsh
        run: |
          xmake global --clean
          xmake f -y -p windows -a x64 -m debug
          xmake build -y tests
          xmake build -y main
