name: ci

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux-nix:
    name: linux (devenv)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Install devenv.sh
        uses: devenv-io/devenv-action@v1

      - name: Build tests and main
        run: |
          xmake global --clean
          xmake f -y -p linux -a x86_64 -m debug
          xmake build -y tests
          xmake build -y main

  windows:
    name: windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build tests and main
        shell: pwsh
        run: |
          xmake global --clean
          xmake f -y -p windows -a x64 -m debug
          xmake build -y tests
          xmake build -y main
